import csv

data = [
    [{"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "b1", "rank": 1, "file": 2},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "c3", "rank": 3, "file": 3},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "c3", "rank": 3, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "b1", "rank": 1, "file": 2},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "a3", "rank": 3, "file": 1},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "a3", "rank": 3, "file": 1}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "b1", "rank": 1, "file": 2},
      "end": {"timeline": 0, "turn": 2, "player": "white", "coordinate": "b3", "rank": 3, "file": 2}, "player": "white",
      "realEnd": {"timeline": 2, "turn": 2, "player": "black", "coordinate": "b3", "rank": 3, "file": 2}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "c1", "rank": 1, "file": 3},
      "end": {"timeline": 0, "turn": 2, "player": "white", "coordinate": "c2", "rank": 2, "file": 3}, "player": "white",
      "realEnd": {"timeline": 2, "turn": 2, "player": "black", "coordinate": "c2", "rank": 2, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "c1", "rank": 1, "file": 3},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "c3", "rank": 3, "file": 3}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "c3", "rank": 3, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "d1", "rank": 1, "file": 4},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "c2", "rank": 2, "file": 3},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "c2", "rank": 2, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "d1", "rank": 1, "file": 4},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "b3", "rank": 3, "file": 2},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "b3", "rank": 3, "file": 2}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "d1", "rank": 1, "file": 4},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "a4", "rank": 4, "file": 1},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "a4", "rank": 4, "file": 1}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "d1", "rank": 1, "file": 4},
      "end": {"timeline": 0, "turn": 2, "player": "white", "coordinate": "c2", "rank": 2, "file": 3}, "player": "white",
      "realEnd": {"timeline": 2, "turn": 2, "player": "black", "coordinate": "c2", "rank": 2, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "g1", "rank": 1, "file": 7},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "h3", "rank": 3, "file": 8},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "h3", "rank": 3, "file": 8}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "g1", "rank": 1, "file": 7},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "f3", "rank": 3, "file": 6},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "f3", "rank": 3, "file": 6}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "g1", "rank": 1, "file": 7},
      "end": {"timeline": 0, "turn": 2, "player": "white", "coordinate": "g3", "rank": 3, "file": 7}, "player": "white",
      "realEnd": {"timeline": 2, "turn": 2, "player": "black", "coordinate": "g3", "rank": 3, "file": 7}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "a2", "rank": 2, "file": 1},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "a3", "rank": 3, "file": 1},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "a3", "rank": 3, "file": 1}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "a2", "rank": 2, "file": 1},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "a4", "rank": 4, "file": 1},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "a4", "rank": 4, "file": 1}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "b2", "rank": 2, "file": 2},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "b3", "rank": 3, "file": 2},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "b3", "rank": 3, "file": 2}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "b2", "rank": 2, "file": 2},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "b4", "rank": 4, "file": 2},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "b4", "rank": 4, "file": 2}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "d2", "rank": 2, "file": 4},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "d3", "rank": 3, "file": 4},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "d3", "rank": 3, "file": 4}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "d2", "rank": 2, "file": 4},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "d4", "rank": 4, "file": 4},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "d4", "rank": 4, "file": 4}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "e2", "rank": 2, "file": 5},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "e3", "rank": 3, "file": 5},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "e3", "rank": 3, "file": 5}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "e2", "rank": 2, "file": 5},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "e4", "rank": 4, "file": 5},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "e4", "rank": 4, "file": 5}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "f2", "rank": 2, "file": 6},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "f3", "rank": 3, "file": 6},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "f3", "rank": 3, "file": 6}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "f2", "rank": 2, "file": 6},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "f4", "rank": 4, "file": 6},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "f4", "rank": 4, "file": 6}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "g2", "rank": 2, "file": 7},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "g3", "rank": 3, "file": 7},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "g3", "rank": 3, "file": 7}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "g2", "rank": 2, "file": 7},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "g4", "rank": 4, "file": 7},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "g4", "rank": 4, "file": 7}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "h2", "rank": 2, "file": 8},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "h3", "rank": 3, "file": 8},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "h3", "rank": 3, "file": 8}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "h2", "rank": 2, "file": 8},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "h4", "rank": 4, "file": 8},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "h4", "rank": 4, "file": 8}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "c4", "rank": 4, "file": 3},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "c5", "rank": 5, "file": 3},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "c5", "rank": 5, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "b1", "rank": 1, "file": 2},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "c3", "rank": 3, "file": 3}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "c3", "rank": 3, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "b1", "rank": 1, "file": 2},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "a3", "rank": 3, "file": 1}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "a3", "rank": 3, "file": 1}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "b1", "rank": 1, "file": 2},
      "end": {"timeline": 0, "turn": 2, "player": "white", "coordinate": "b3", "rank": 3, "file": 2}, "player": "white",
      "realEnd": {"timeline": 2, "turn": 2, "player": "black", "coordinate": "b3", "rank": 3, "file": 2}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "c1", "rank": 1, "file": 3},
      "end": {"timeline": 0, "turn": 2, "player": "white", "coordinate": "c2", "rank": 2, "file": 3}, "player": "white",
      "realEnd": {"timeline": 2, "turn": 2, "player": "black", "coordinate": "c2", "rank": 2, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "c1", "rank": 1, "file": 3},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "c3", "rank": 3, "file": 3},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "c3", "rank": 3, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "d1", "rank": 1, "file": 4},
      "end": {"timeline": 0, "turn": 2, "player": "white", "coordinate": "c2", "rank": 2, "file": 3}, "player": "white",
      "realEnd": {"timeline": 2, "turn": 2, "player": "black", "coordinate": "c2", "rank": 2, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "d1", "rank": 1, "file": 4},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "b3", "rank": 3, "file": 2},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "b3", "rank": 3, "file": 2}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "g1", "rank": 1, "file": 7},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "h3", "rank": 3, "file": 8}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "h3", "rank": 3, "file": 8}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "g1", "rank": 1, "file": 7},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "f3", "rank": 3, "file": 6}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "f3", "rank": 3, "file": 6}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "g1", "rank": 1, "file": 7},
      "end": {"timeline": 0, "turn": 2, "player": "white", "coordinate": "g3", "rank": 3, "file": 7}, "player": "white",
      "realEnd": {"timeline": 2, "turn": 2, "player": "black", "coordinate": "g3", "rank": 3, "file": 7}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "a2", "rank": 2, "file": 1},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "a3", "rank": 3, "file": 1}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "a3", "rank": 3, "file": 1}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "a2", "rank": 2, "file": 1},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "a4", "rank": 4, "file": 1}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "a4", "rank": 4, "file": 1}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "c2", "rank": 2, "file": 3},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "c3", "rank": 3, "file": 3}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "c3", "rank": 3, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "c2", "rank": 2, "file": 3},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "c4", "rank": 4, "file": 3}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "c4", "rank": 4, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "c2", "rank": 2, "file": 3},
      "end": {"timeline": 0, "turn": 2, "player": "white", "coordinate": "c2", "rank": 2, "file": 3}, "player": "white",
      "realEnd": {"timeline": 2, "turn": 2, "player": "black", "coordinate": "c2", "rank": 2, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "c2", "rank": 2, "file": 3},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "c2", "rank": 2, "file": 3},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "c2", "rank": 2, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "d2", "rank": 2, "file": 4},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "d3", "rank": 3, "file": 4}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "d3", "rank": 3, "file": 4}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "d2", "rank": 2, "file": 4},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "d4", "rank": 4, "file": 4}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "d4", "rank": 4, "file": 4}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "e2", "rank": 2, "file": 5},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "e3", "rank": 3, "file": 5}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "e3", "rank": 3, "file": 5}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "e2", "rank": 2, "file": 5},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "e4", "rank": 4, "file": 5}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "e4", "rank": 4, "file": 5}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "f2", "rank": 2, "file": 6},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "f3", "rank": 3, "file": 6}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "f3", "rank": 3, "file": 6}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "f2", "rank": 2, "file": 6},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "f4", "rank": 4, "file": 6}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "f4", "rank": 4, "file": 6}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "g2", "rank": 2, "file": 7},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "g3", "rank": 3, "file": 7}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "g3", "rank": 3, "file": 7}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "g2", "rank": 2, "file": 7},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "g4", "rank": 4, "file": 7}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "g4", "rank": 4, "file": 7}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "h2", "rank": 2, "file": 8},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "h3", "rank": 3, "file": 8}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "h3", "rank": 3, "file": 8}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "h2", "rank": 2, "file": 8},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "h4", "rank": 4, "file": 8}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "h4", "rank": 4, "file": 8}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "b3", "rank": 3, "file": 2},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "d4", "rank": 4, "file": 4}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "d4", "rank": 4, "file": 4}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "b3", "rank": 3, "file": 2},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "c5", "rank": 5, "file": 3}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "c5", "rank": 5, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "b3", "rank": 3, "file": 2},
      "end": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "a5", "rank": 5, "file": 1}, "player": "white",
      "realEnd": {"timeline": 1, "turn": 2, "player": "black", "coordinate": "a5", "rank": 5, "file": 1}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "b3", "rank": 3, "file": 2},
      "end": {"timeline": 0, "turn": 2, "player": "white", "coordinate": "d3", "rank": 3, "file": 4}, "player": "white",
      "realEnd": {"timeline": 2, "turn": 2, "player": "black", "coordinate": "d3", "rank": 3, "file": 4}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "b3", "rank": 3, "file": 2},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "c3", "rank": 3, "file": 3},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "c3", "rank": 3, "file": 3}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "b3", "rank": 3, "file": 2},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "a3", "rank": 3, "file": 1},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "a3", "rank": 3, "file": 1}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "b3", "rank": 3, "file": 2},
      "end": {"timeline": 0, "turn": 2, "player": "white", "coordinate": "b5", "rank": 5, "file": 2}, "player": "white",
      "realEnd": {"timeline": 2, "turn": 2, "player": "black", "coordinate": "b5", "rank": 5, "file": 2}},
     {"promotion": None, "enPassant": None, "castling": None,
      "start": {"timeline": 1, "turn": 2, "player": "white", "coordinate": "b3", "rank": 3, "file": 2},
      "end": {"timeline": -1, "turn": 2, "player": "white", "coordinate": "b4", "rank": 4, "file": 2},
      "player": "white",
      "realEnd": {"timeline": -1, "turn": 2, "player": "black", "coordinate": "b4", "rank": 4, "file": 2}}]

]

# Flatten the nested structure
flattened_data = []
for move in data[0]:
 flattened_move = {
  'promotion': move['promotion'],
  'enPassant': move['enPassant'],
  'castling': move['castling'],
  'start_timeline': move['start']['timeline'],
  'start_turn': move['start']['turn'],
  'start_player': move['start']['player'],
  'start_coordinate': move['start']['coordinate'],
  'start_rank': move['start']['rank'],
  'start_file': move['start']['file'],
  'end_timeline': move['end']['timeline'],
  'end_turn': move['end']['turn'],
  'end_player': move['end']['player'],
  'end_coordinate': move['end']['coordinate'],
  'end_rank': move['end']['rank'],
  'end_file': move['end']['file'],
  'player': move['player'],
  'realEnd_timeline': move['realEnd']['timeline'],
  'realEnd_turn': move['realEnd']['turn'],
  'realEnd_player': move['realEnd']['player'],
  'realEnd_coordinate': move['realEnd']['coordinate'],
  'realEnd_rank': move['realEnd']['rank'],
  'realEnd_file': move['realEnd']['file']
 }
 flattened_data.append(flattened_move)

# Write to CSV
with open('chess_moves.csv', 'w', newline='') as csvfile:
 fieldnames = flattened_data[0].keys()
 writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

 writer.writeheader()
 for row in flattened_data:
  writer.writerow(row)

print("CSV file 'chess_moves.csv' has been created successfully.")